services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"  # Important: UDP for HTTP/3/QUIC
      - "2019:2019"  # Caddy admin interface
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
      - VITE_API_URL=http://localhost:8080/api
      - NODE_ENV=production
      - REACT_APP_ENV=productionss
      - VITE_ENV=production
      - REACT_APP_VERSION=1.0.0
      - VITE_VERSION=1.0.0
    
    volumes:
      - ./ssl:/etc/nginx/ssl/
      - ./nginx2.conf:/etc/nginx/nginx.conf:ro
      - ./entrypoint.sh:/entrypoint.sh

 